version: '3.8'
services:
  mysql-test:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_DATABASE: ecommerce_test
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    tmpfs:
      - /var/lib/mysql
